preserve_hierarchy: true

files:
  - source: 'sources/15w14a/en_US.lang'
    translation: /resources/15w14a/assets/minecraft/lang/%locale%.lang

  - source: 'sources/1.RV-Pre1/en_us.lang'
    translation: /resources/1.RV-Pre1/assets/minecraft/lang/%locale_with_underscore%.lang

  - source: 'sources/**/en_us.json'
    translation: /resources/%file_name%/assets/minecraft/lang/%locale_with_underscore%.json

