name: Auto Build and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Zip Each Folder in Resources
        run: |
          UPLOAD_FILES=""
          for dir in ./resources/*; do
            if [ -d "$dir" ]; then
              folder_name=$(basename "$dir")
              zip_file="${folder_name}.zip"
              zip -r "$zip_file" "$dir" || echo "Skipping empty folder: $dir"
              UPLOAD_FILES="$UPLOAD_FILES $zip_file"
            fi
          done
          echo "UPLOAD_FILES=$UPLOAD_FILES" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          release_name: "Build ${{ github.run_number }}"
          body: |
            自动构建的资源包。
            - Run ID: ${{ github.run_id }}
            - Commit SHA: ${{ github.sha }}
          files: |
            23w13a_or_b.zip
            24w14potato.zip
            25w14craftmine.zip