name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache zip Installation
        uses: actions/cache@v3
        with:
          path: /usr/bin/zip
          key: ubuntu-zip-cache

      - name: Install zip if Not Cached
        run: sudo apt-get install -y zip

      - name: Build Info
        run: |
          echo "Run ID: ${{ github.run_id }}" > build-info.txt
          echo "Run Number: ${{ github.run_number }}" >> build-info.txt
          echo "Commit SHA: ${{ github.sha }}" >> build-info.txt
          echo "Repository: ${{ github.repository }} (${{ github.repository_id }})" >> build-info.txt
          echo "Repository URL: ${{ github.repositoryUrl }}" >> build-info.txt
          echo "Triggered by: ${{ github.actor }} (${{ github.actor_id }})" >> build-info.txt

      - name: Zip Each Folder in Resources and Upload
        run: |
          for dir in ./resources/*/; do
            folder_name=$(basename "$dir")
            if [ -d "$dir" ]; then
              zip_file="${folder_name}.zip"
              zip -r "$zip_file" "$dir" || echo "Skipping empty folder: $dir"

              # Upload each zip file as an artifact
              echo "Uploading $zip_file..."
              gh release upload "build-${{ github.run_number }}" "$zip_file" --clobber
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
