name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install zip

      - name: Build Info
        run: |
          echo "Run ID: ${{ github.run_id }}" > build-info.txt
          echo "Run Number: ${{ github.run_number }}" >> build-info.txt
          echo "Commit SHA: ${{ github.sha }}" >> build-info.txt
          echo "Repository: ${{ github.repository }} (${{ github.repository_id }})" >> build-info.txt
          echo "Repository URL: ${{ github.repositoryUrl }}" >> build-info.txt
          echo "Triggered by: ${{ github.actor }} (${{ github.actor_id }})" >> build-info.txt

      - name: Zip Each Folder in Resources
        run: |
          for dir in ./resources/*/; do
            folder_name=$(basename "$dir")
            zip -r "${folder_name}.zip" "$dir"
          done

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Zipped-Folders
          path: ./*.zip
