name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache zip Installation
        uses: actions/cache@v3
        with:
          path: /usr/bin/zip
          key: ubuntu-zip-cache

      - name: Install zip if Not Cached
        run: sudo apt-get install -y zip

      - name: Build Info
        run: |
          echo "Run ID: ${{ github.run_id }}" > build-info.txt
          echo "Run Number: ${{ github.run_number }}" >> build-info.txt
          echo "Commit SHA: ${{ github.sha }}" >> build-info.txt
          echo "Repository: ${{ github.repository }} (${{ github.repository_id }})" >> build-info.txt
          echo "Repository URL: ${{ github.repositoryUrl }}" >> build-info.txt
          echo "Triggered by: ${{ github.actor }} (${{ github.actor_id }})" >> build-info.txt

      - name: Zip Each Folder in Resources
        run: |
          for dir in ./resources/*/; do
            folder_name=$(basename "$dir")
            if [ -d "$dir" ]; then
              zip -r "${folder_name}.zip" "$dir" || echo "Skipping empty folder: $dir"
            fi
          done

      - name: Combine All Zips into One Archive
        run: zip -r combined-zipped-folders.zip ./*.zip

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Combined-Zipped-Folders
          path: ./combined-zipped-folders.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "build-${{ github.run_number }}"
          release_name: "Build ${{ github.run_number }}"
          body: |
            自动构建的资源包。
            - Run ID: ${{ github.run_id }}
            - Commit SHA: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./combined-zipped-folders.zip
          asset_name: Combined-Zipped-Folders.zip
          asset_content_type: application/zip
