name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        pack-version: ["23w13a_or_b", "24w14potato", "25w14craftmine"]

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    outputs:
      output1: ${{ steps.create_release.outputs.id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pack ${{ matrix.pack-version }}
        run: |
          cd resources/${{ matrix.pack-version }}
          zip -r ../../${{ matrix.pack-version }}.zip ./*

      - name: Upload Release for ${{ matrix.pack-version }}
        uses: xresloader/upload-to-github-release@v1
        with:
          file: '*.zip'
          overwrite: true

          
          
